version: "3"
services:
  node:
    environment:
      - TEZOS_HISTORY_MODE
    image: tezos/tezos:v${TEZOS_VERSION}
    entrypoint: "tezos-node"
    command: "run --data-dir /var/run/tezos/node/data --history-mode ${TEZOS_HISTORY_MODE:-rolling} --rpc-addr 0.0.0.0:8732 --allow-all-rpc=0.0.0.0:8732 --cors-header='content-type' --cors-origin='*'"
    hostname: node
    ports:
      - "8732:8732"
      - "9732:9732/udp"
    volumes:
       - "/tezos/node:/var/run/tezos/node"
